add_newline = false
command_timeout = 800
format = "$directory$os$git_branch$git_status$character"

[os]
disabled = false
style = "bold #89b4fa"

[os.symbols]
Windows = "🔰 "

[directory]
style = "bold #cba6f7"
truncation_length = 3
truncate_to_repo = false
read_only = " [ro]"

[git_branch]
symbol = ""
format = "[$symbol$branch]($style)"
style = "bold #a6e3a1"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "bold #fab387"

[character]
success_symbol = "[❯](bold #89b4fa)"
error_symbol = "[❯](bold #f38ba8)"
vimcmd_symbol = "[❮](bold #89b4fa)"
