add_newline = false
command_timeout = 800
format = "$directory$os$git_branch$git_status$character"

[os]
disabled = false
style = "bold #81a1c1"

[os.symbols]
Windows = "🔰 "

[directory]
style = "bold #81a1c1"
truncation_length = 3
truncate_to_repo = false
read_only = " [ro]"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style)"
style = "bold #a3be8c"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "bold #d08770"

[character]
success_symbol = "[❯](bold #81a1c1)"
error_symbol = "[❯](bold #bf616a)"
vimcmd_symbol = "[❮](bold #81a1c1)"
